name: Increment Version

on:
    workflow_dispatch:
        inputs:
            old-version:
                description: "old-version"
                required: true
                default: "0.25.0"
            release-version:
                description: "release-version"
                required: true
                default: "0.25.1"

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Run Python Script
              run: |
                  git config user.name '${{ github.actor }}'
                  git config user.email '${{ github.actor }}@users.noreply.github.com'
                  python release.py --release-version "${{ inputs.release-version }}" --old-version "${{ inputs.old-version }}"
                  git push origin
